### ISSUE TITLE
Handle files without the tag

### ISSUE THREAD

**Issue by 6farer** [stephenoken/gulp-remove-html#2]
index.js line 31
```
            if (indices.length === 0) {
              this.emit('error', new PluginError(PLUGIN_NAME, 'File does not contain the right tag'));
              return cb();
            }
```
Does this throw an error if a file doesn't have any deject tags? I'm trying to pipe all my html through and some files don't have any deject tags.

**Comment by stephenoken** [comment]
The plugin did throw an error when files were passed through without the `!--<Deject>-->` tag. The bug has been patched now and a new version is available on NPM. 
Sorry about taking so long to respond to this issue and thanks for bringing it up!

![cheers!](https://media.giphy.com/media/3o85xL32sNUfjqgqpa/giphy.gif)
